name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java Version 14.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
      - name: Run all feature files
        run: mvn clean install && mvn exec:java -Dexec.classpathScope=test -Dexec.mainClass=io.cucumber.core.cli.Main -Dexec.args="src/test/java/features --glue steps"
